[package]
name = "tree"
version = "0.1.0"
authors = ["Cartesi Team"]
homepage = "https://cartesi.io"
edition = "2018"

[dependencies]
async-trait = "0.1"
dispatcher = { path = "../dispatcher-v2/dispatcher"}
state_actor = { path = "../dispatcher-v2/state_actor"}
utils = { path = "../dispatcher-v2/utils"}
ethabi = "12.0"
ethereum-types = "0.9"
futures = "0.3"
im = "15.0"
snafu = "0.6"
tokio = { version = "0.2", features = ["full"] }
web3 = { git = "https://github.com/tomusdrw/rust-web3" }
