name: Build
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
                  token: ${{ secrets.CI_TOKEN }}
            - uses: actions/setup-node@v3
              with:
                  node-version: "16"
            - run: yarn install
            - run: yarn prepack
            - run: yarn prettier
            - run: yarn test:coverage
